version: "3.4"
services:
  backend:
    image: rocketdynamics/rocketboard:${VERSION:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      FIRESTORE_EMULATOR_HOST: firestore:8509
      PUBSUB_EMULATOR_HOST: pubsub:8510
    ports:
    - 5000:5000
    depends_on:
    - firestore
    - pubsub

  frontend-tests:
    image: rocketdynamics/rocketboard-frontend:${VERSION:-latest}
    command: yarn test
    init: true
    cap_add:
    - SYS_ADMIN
    volumes:
    - ./traceshots:/frontend/traceshots
    ports:
    - 3000:3000
    build:
      context: .
      dockerfile: Dockerfile.frontend
      target: frontend-builder
    environment:
      TARGET_URL: http://localhost:3000
    depends_on:
    - backend

  backend-tests:
    image: rocketdynamics/rocketboard-tests:${VERSION:-latest}
    command: go test -v ./... -cover
    build:
      context: .
      dockerfile: Dockerfile
      target: backend-builder
    environment:
      FIRESTORE_EMULATOR_HOST: firestore:8509
      PUBSUB_EMULATOR_HOST: pubsub:8510
    depends_on:
    - firestore
    - pubsub

  firestore:
    image: google/cloud-sdk:latest
    command: gcloud beta emulators firestore start --host-port=0.0.0.0:8509

  pubsub:
    image: google/cloud-sdk:latest
    command: gcloud beta emulators pubsub start --host-port=0.0.0.0:8510
