apiVersion: v1
kind: Service
metadata:
  name: {{ template "rocketboard.fullname" . }}
  labels:
    app: {{ template "rocketboard.name" . }}
    chart: {{ template "rocketboard.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if index .Values "include-qa-annotations" }}
  annotations:
    com.arachnys.qa-portal.host: {{ index .Values "oauth2-proxy" "ingress" "hosts" 0 }}
    com.arachnys.qa-portal.app: {{ template "rocketboard.name" . }}
    com.arachnys.qa-portal.version: "{{ .Values.image.tag }}"
{{- end }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "rocketboard.name" . }}
    release: {{ .Release.Name }}
