replicaCount: 3

include-qa-annotations: false

nats:
  replicaCount: 3

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 3
    maxUnavailable: 0

cockroachdb:
  enabled: true
  Replicas: 3
  Storage: 10Gi
  Resources:
    requests:
      cpu: "100m"
      memory: "2Gi"
    limits:
      cpu: "1000m"
      memory: "2Gi"

oauth2-proxy:
  replicaCount: 1

  service:
    port: 4180

  ingress:
    enabled: true
    path: /oauth2
    hosts:
      - rocketboard.example.com
    tls:
      - secretName: example-wildcard-tls
        hosts:
          - rocketboard.example.com

  config:
    clientID: oauth_client_id
    clientSecret: client_secret
    cookieSecret: cookie_seceret
    htpasswdFile: |
      rocketboard:$2y$05$T2OACR4TjxMLqY66FE6UV.dROuGpLTbdPv1cyzIlzk86JxkKuzmH2

  extraArgs:
    oidc-issuer-url: "https://oauth.example.com"
    provider: "oidc"
    upstream: "http://rocketboard"
    http-address: "0.0.0.0:4180"

